export const START_LOADING = 'loading/START_LOADING';
export const FINISH_LOADING = 'loading/FINISH_LOADING';

export const SIGNIN = 'auth/SIGNIN';
export const SIGNIN_SUCCESS = 'auth/SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'auth/SIGNIN_FAILURE';

export const SIGNUP = 'auth/SIGNUP';
export const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'auth/SIGNUP_FAILURE';

export const SIGNOUT = 'auth/SIGNOUT';
export const SIGNOUT_SUCCESS = 'auth/SIGNOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'auth/SIGNOUT_FAILURE';

export const CHECKSIGNIN = 'auth/CHECKSIGNIN';
export const CHECKSIGNIN_SUCCESS = 'auth/CHECKSIGNIN_SUCCESS';
export const CHECKSIGNIN_FAILURE = 'auth/CHECKSIGNIN_FAILURE';

export const GETMEETINGS = 'meetings/GETMEETINGS';
export const GETMEETINGS_SUCCESS = 'meetings/GETMEETINGS_SUCCESS';
export const GETMEETINGS_FAILURE = 'meetings/GETMEETINGS_FAILURE';

export const CREATEMEETING = 'meetings/CREATEMEETING';
export const CREATEMEETING_SUCCESS = 'meetings/CREATEMEETING_SUCCESS';
export const CREATEMEETING_FAILURE = 'meetings/CREATEMEETING_FAILURE';

export const EDITMEETING = 'meetings/EDITMEETING';
export const EDITMEETING_SUCCESS = 'meetings/EDITMEETING_SUCCESS';
export const EDITMEETING_FAILURE = 'meetings/EDITMEETING_FAILURE';

export const DELETEMEETING = 'meetings/DELETEMEETING';
export const DELETEMEETING_SUCCESS = 'meetings/DELETEMEETING_SUCCESS';
export const DELETEMEETING_FAILURE = 'meetings/DELETEMEETING_FAILURE';

export const TOGGLEMEETING = 'meetings/TOGGLEMEETING';
export const TOGGLEMEETING_SUCCESS = 'meetings/TOGGLEMEETING_SUCCESS';
export const TOGGLEMEETING_FAILURE = 'meetings/TOGGLEMEETING_FAILURE';

export const GETROOMCOMMENTS = 'comments/GETROOMCOMMENTS';
export const GETROOMCOMMENTS_SUCCESS = 'comments/GETROOMCOMMENTS_SUCCESS';
export const GETROOMCOMMENTS_FAILURE = 'comments/GETROOMCOMMENTS_FAILURE';

export const GETMEETINGCOMMENTS = 'comments/GETMEETINGCOMMENTS';
export const GETMEETINGCOMMENTS_SUCCESS = 'comments/GETMEETINGCOMMENTS_SUCCESS';
export const GETMEETINGCOMMENTS_FAILURE = 'comments/GETMEETINGCOMMENTS_FAILURE';

export const CREATECOMMENT = 'comments/CREATECOMMENT';
export const CREATECOMMENT_SUCCESS = 'comments/CREATECOMMENT_SUCCESS';
export const CREATECOMMENT_FAILURE = 'comments/CREATECOMMENT_FAILURE';

export const EDITCOMMENT = 'comments/EDITCOMMENT';
export const EDITCOMMENT_SUCCESS = 'comments/EDITCOMMENT_SUCCESS';
export const EDITCOMMENT_FAILURE = 'comments/EDITCOMMENT_FAILURE';

export const DELETECOMMENT = 'comments/DELETECOMMENT';
export const DELETECOMMENT_SUCCESS = 'comments/DELETECOMMENT_SUCCESS';
export const DELETECOMMENT_FAILURE = 'comments/DELETECOMMENT_FAILURE';
