# Generated by Django 3.2.7 on 2021-11-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_meeting_author'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='meeting',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='meeting.meeting'),
        ),
    ]
