# Generated by Django 3.2.7 on 2021-11-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_id'),
        ('comment', '0004_auto_20211125_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='room.room'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
