# Generated by Django 3.2.7 on 2021-11-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_meeting_author'),
        ('meeting', '0003_auto_20211119_0559'),
    ]

    operations = [
    ]
