# Generated by Django 3.1.2 on 2021-11-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_merge_20211124_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
