# Generated by Django 3.2.7 on 2021-11-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_merge_20211125_1729'),
        ('meeting', '0006_auto_20211125_1658'),
    ]

    operations = [
    ]
