# Generated by Django 3.2.7 on 2021-12-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=4)),
                ('day', models.CharField(max_length=4)),
                ('current_mem_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('dates', models.TextField(null=True)),
            ],
        ),
    ]
