# Generated by Django 3.1.2 on 2021-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20211208_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
