# Generated by Django 3.1.2 on 2021-12-09 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_auto_20211208_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='Hello!', max_length=200)),
                ('request_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_date', to='room.date')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_of_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
